<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RANJIT" failures="1" tests="9" name="cucumberOptions.TestRunner" time="50.323" errors="0" timestamp="2024-12-02T22:14:57 IST" skipped="0">
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="3.264"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="3.992"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="3.389"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="3.810"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="4.179"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="3.519"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="8.902"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="15.716"/>
  <system-out/>
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="3.552">
    <failure message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at stepDefinations.LoginPageSteps.user_is_logged_in(LoginPageSteps.java:99)
at âœ½.user is logged in(file:///D:/RestAssured/BddFrameWork/src/test/java/featureLayer/Login.feature:20)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- cucumberOptions.TestRunner -->
